name: openwrt

on:
  push:
    branches: 
      - master
env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: dev-19.07
  CONFIG_FILE: x86.config
  DIY_SH: diy.sh
  FREE_UP_DISK: false
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-7 gcc++-7 gcc-7-multilib g++-7-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
    - name: Init source
      run: |
        cd /home/runner
        git clone https://github.com/project-openwrt/openwrt.git
        sudo chown -R runner:runner openwrt
        cd /home/runner/openwrt
        ./scripts/feeds update -a 
        ./scripts/feeds install -a
      
    #- name: SSH connection to Actions
    #  uses: P3TERX/debugger-action@master
     # if: env.SSH_ACTIONS == 'true'
    - name: Before Build
      run: |
        /bin/bash /home/runner/work/build-openwrt/build-openwrt/before_build.sh
        cp -fpR /home/runner/work/build-openwrt/build-openwrt/. /home/runner/openwrt/
    - name: Start Build
      run: | 
        cd /home/runner/openwrt
        let make_process=$(nproc)+1
        mv .config .config_default
        rm -f .config.old
        config_names="$(ls .config*)"
        for i in $config_names;do mv -f $i .config; make defconfig; make -j${make_process}; rm -rf build_dir/target* build_dir/toolchain* staging_dir/target* staging_dir/toolchain*; done
    - name: After Build
      run: |
        /bin/bash /home/runner/openwrt/after_build.sh
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /home/runner/openwrt/bin
